live_config_reload = true
import = ["~/.cache/wal/colors-alacritty.toml"]


[cursor]
style = "Block"

[env]
TERM = "alacritty"

[font]
size = 22

[font.normal]
family = "HackGen Console NF"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.8
blur = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 45

[window.padding]
x = 5
y = 0
